### ISSUE TITLE
Adapter crashes due to unhandled promise rejection

### ISSUE THREAD

**Issue by KenADev** [arteck/ioBroker.hs100#87]
**Describe the bug**  
I have a HS110 installed behind a fridge that sometimes loses its wifi connection to the router, which is okay for me actually.

However, the hs100 adapter doesn't like it at all. It detects the TCP timeout, but then crashes with an UNHANDLED_EXCEPTION (Code 6) because there is an unhandled promise rejection.
If the HS110 is unavailable for a few minutes, the adapter repeatedly crashes and is completely stopped by iobroker at some point.

**To Reproduce**  
1.) Disconnect HS110 from Network/Power Socket
2.) Watch what happens in log console after some time

**Expected behavior**  
The adapter should handle the TCP timeout exception and not crash.

**Screenshots & Logfiles**  
```
2021-04-08 10:34:56.617  - info: host.raspi04 instance system.adapter.hs100.0 started with pid 20095
2021-04-08 10:34:58.167  - info: hs100.0 (20095) starting. Version 2.0.1 in /opt/iobroker/node_modules/iobroker.hs100, node: v14.16.1, js-controller: 3.2.16
2021-04-08 10:34:58.306  - info: hs100.0 (20095) Start with IP : 192.168.4.3
2021-04-08 10:34:58.449  - warn: hs100.0 (20095) State "hs100.0.info.connection" has no existing object, this might lead to an error in future versions
2021-04-08 10:34:58.603  - warn: hs100.0 (20095) State "hs100.0.info.connection" has no existing object, this might lead to an error in future versions
2021-04-08 10:35:09.290  - error: hs100.0 (20095) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
2021-04-08 10:35:09.290  - error: hs100.0 (20095) unhandled promise rejection: TCP Timeout
2021-04-08 10:35:09.291  - error: hs100.0 (20095) Error: TCP Timeout
2021-04-08 10:35:09.292  - error: hs100.0 (20095) TCP Timeout
2021-04-08 10:35:09.329  - info: hs100.0 (20095) cleaned everything up...
2021-04-08 10:35:09.330  - info: hs100.0 (20095) terminating
2021-04-08 10:35:09.332  - warn: hs100.0 (20095) Terminated (UNCAUGHT_EXCEPTION): Without reason
2021-04-08 10:35:09.334  - warn: hs100.0 (20095) State "hs100.0.info.connection" has no existing object, this might lead to an error in future versions
2021-04-08 10:35:09.902  - error: host.raspi04 instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

```
**Versions:**  
 - Adapter version: 2.0.1
 - JS-Controller version: 3.2.16
 - Node version: v14.16.0
 - Operating system: raspbian buster

**Additional context**  
does not apply

**Comment by arteck** [comment]
plz check new version

**Comment by LaplaceII** [comment]
Still the same problem. Adapter crashes after timeouts randomly. Even a daily regular restart of the adapter does not work.
`host.rock64 | 2021-05-16 16:04:22.861 | info | instance system.adapter.hs100.0 started with pid 3963
-- | -- | -- | --
host.rock64 | 2021-05-16 16:04:21.802 | info | Restart adapter system.adapter.hs100.0 because enabled
host.rock64 | 2021-05-16 16:04:21.800 | error | instance system.adapter.hs100.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.rock64 | 2021-05-16 16:04:21.800 | error | Caught by controller[2]: at processTimers (internal/timers.js:497:7)
host.rock64 | 2021-05-16 16:04:21.799 | error | Caught by controller[2]: at listOnTimeout (internal/timers.js:554:17)
host.rock64 | 2021-05-16 16:04:21.798 | error | Caught by controller[2]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
host.rock64 | 2021-05-16 16:04:21.797 | error | Caught by controller[2]: 192.168.1.51:9999 {"emeter":{"get_daystat":{"year":2021,"month":5}}}
host.rock64 | 2021-05-16 16:04:21.797 | error | Caught by controller[2]: [EG_KUE_Spuelmaschine] device.send() Error: TCP Timeout after 10000ms
host.rock64 | 2021-05-16 16:04:21.796 | error | Caught by controller[1]: at processTimers (internal/timers.js:497:7)
host.rock64 | 2021-05-16 16:04:21.795 | error | Caught by controller[1]: at listOnTimeout (internal/timers.js:554:17)
host.rock64 | 2021-05-16 16:04:21.795 | error | Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-socket.js:59:36)
host.rock64 | 2021-05-16 16:04:21.794 | error | Caught by controller[1]: 192.168.1.51:9999 {"emeter":{"get_daystat":{"year":2021,"month":5}}}
host.rock64 | 2021-05-16 16:04:21.793 | error | Caught by controller[1]: TCP 192.168.1.51:9999 Error: TCP Timeout after 10000ms
hs100.0 | 2021-05-16 16:04:20.915 | warn | (4831) Terminated (UNCAUGHT_EXCEPTION): Without reason
hs100.0 | 2021-05-16 16:04:20.839 | error | (4831) TCP Timeout after 10000ms 192.168.1.51:9999 {"emeter":{"get_daystat":{"year":2021,"month":5}}}
hs100.0 | 2021-05-16 16:04:20.838 | error | (4831) Error: TCP Timeout after 10000ms 192.168.1.51:9999 {"emeter":{"get_daystat":{"year":2021,"month":5}}} at Timeout._onTimeout (/opt/iobroker/node_modules/tplink-smarthome-api/lib/network/tcp-
hs100.0 | 2021-05-16 16:04:20.836 | error | (4831) unhandled promise rejection: TCP Timeout after 10000ms 192.168.1.51:9999 {"emeter":{"get_daystat":{"year":2021,"month":5}}}
hs100.0 | 2021-05-16 16:04:20.835 | error | (4831) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

**Comment by arteck** [comment]
and after restart you rock64

**Comment by LaplaceII** [comment]
Unfortunately no change by restart.

**Comment by leepfrog-ger** [comment]
Having the same issue on 2.0.3 (which is the most up to date version in the iobroker repo).

What's the procedure to get to 2.0.4 from there?

**Comment by KenADev** [comment]
I also still have the same problem with 2.0.3, should it be fixed there @arteck? In which commit did you fix it?

**Comment by ddsak** [comment]
Same here. 
Adapter 2.0.4 
JS 3.3.12
Node 12.22.1

**Comment by arteck** [comment]
the problem is the dependency tplink-smarthome-api.. not the adapter ..

**Comment by KenADev** [comment]
Even if that is the case, your adapter would jist have to wrap a try-catch block around the method from the other lib in order to handle this exception

**Comment by arteck** [comment]
all requests have a try catch block.. the problem is the dependency

**Comment by KenADev** [comment]
I think it may be because the adapter uses await on the async client.getDevice method:
`const result = await client.getDevice({host: ip});`
Is there a specific reason to use await here? 
Maybe it works without await and if the promise is handled with .then(...).catch(...) instead?

Here's an article about the async/await promise problem:
https://dev.to/gajus/handling-unhandled-promise-rejections-in-async-functions-5b2b

**Comment by arteck** [comment]
lol.. you can change this in your source..  you will find this is not the problem..

**Comment by arrizer** [comment]
I am observing the same issue. The reason is, that the async function updateDevice() is called without an await keyword:
https://github.com/arteck/ioBroker.hs100/blob/master/main.js#L165

The has the effect that errors thrown from the function cannot be handled by the surrounding catch block, since execution continues without actually waiting for the function to finish or fail. I fixed this and created a pull request:

https://github.com/arteck/ioBroker.hs100/pull/96

**Comment by KenADev** [comment]
This fixed the issue, thank you arrizer!

https://github.com/arteck/ioBroker.hs100/pull/96

**Comment by KenADev** [comment]
Reopening the Issue.
There is no unhandled promise rejection anymore, the adapter stays "green", but it stops listening to the Plug once it lost connection and comes back up again.

**Comment by arteck** [comment]
back to the old version....

**Comment by mklinki** [comment]
Sorry for re-opening this issue again after such a long time but this is exactly the same behaviour like version 2.1.2 is doing on my broker currently.
